language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: dIn8jw5PeGrNtRQxGlkk9+W0SuscxVVQsO4qFzw9rTL6lgIzpEI8UTpTpz7Cc+T/mgOFeMC3ciSEOhtsoKnudrC15doEuFuD/sbOSxdOf+TVhr079BO2FyGqggToqRYvD9g2gHumcESXfgQ7DgQEbzfEesBirfDYUxxUmmPTIxWs3HMUke5BV7GHL25ZG1++L26ezey0EoDlWYN3Rw0Lh+6cLzPYn5ZTK3Rb+XAckUDzbCekSfrhagLlRtHPZRw6UI7jsqEqTlRtKVp66J8pdTllz+I+ye7VbEiJ5Ni43uOBYf0tO0FTmQfVzolfFbmIc0p3W6heQsX43irc0opGIAM7m5E4d6duV04V23e0R3CYOT3Qj5yxNEt2lcDejfZIa6qzxdRM2Eo2jk/OC7bxwLuLWIg681df9v9tCEYi0duHbonjTT2HciqOhTDxOd1OwAPyOi9HDm3b8o1OQnB/5eEDwJ3EBCKpD4QEMzQd3jqIb7HRUz1eYsj2FSsElChdvKiDozVSb3X3B5BF1imSpsilDc2ZHQmIzLu/0r3ITzQ6LrpWt9ixq4/s8uFkneOIMo5E4pUcwRjyyq2+4UwiSQoQSM1cd7RiIj94o2MRYqqtwgQPtnk6SDX+hLiE9BrrbMHXjxIy3ohnGOscHZkxZqjTOzS4Ur1lX/poJSRM6wo=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: ZVpCkIQckOW6NIcffLXpmM8+3tWG/ikwjDN2fkZ74w11CGpiI/jrY+Del9zRPgrddJ6b/m68bvj6ONO7ev0S4O4zIS28jNBjwn2bepd1jXSMh4uD2joz3Q/Ygairxab4NVLUrfIrgMbuj5bX5z4uBgq4Wx5uL7TTZM9FpHg4PRiv9eMwTAhxAvatbVAwXBnlI469hHawkDgkv68FOoybXoyEvfvfC4hxf4MQyfZxU45h0wHvqIZuQlckrreeAWGp6ap2aiRcXbxETl+zqL0Eg3R0MItpu9rdzLIDIwPXDdGp//vy6WnZsx2WozzsY76OMTC/S0wqJCtr8Vvpp829CwuLLLet4weyW6F8J74sSE95c/fwJlD2R1eTgO6BB/tCfxGIOIDRMuUCFaKDYxGL11DT3rApD8zyIbwdqCNnLqQYBUQcydqOVsCXr8TP5kKI7TYAESYd+y9duU3E3tVTbpp4Ngj5r+2onWEtFyGZJc6oIF3751qqaGpf5L349LQCx79faUITMjWZagFYXZmwbDFcb26ue60pUelUMlcnAukJblrELmEx0QUBjtn5T1LKsW/ei9Q4drysDhF0d1cyjHqD2IyRfG7mHcy3I/rwmqX7h/tTPX647rEeDqv9ZI7oqgcvsqT669+WE4lsNJt13GDmJIISb2wmQ9RYDKZNWdM=
      on_success: never
      on_failure: always
      on_pull_requests: false
